Default: &defaults
  database: shoes.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: shoes_test.sqlite3
  <<: *defaults

Staging:
  database: shoes_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: shoes_production.sqlite3
  poolsize: 100
  <<: *defaults
